export const folders = [
  { id: 1, name: "개발", count: 12 },
  { id: 2, name: "디자인", count: 5 },
  { id: 3, name: "유튜브", count: 8 },
  { id: 4, name: "블로그", count: 3 },
  { id: 5, name: "뉴스", count: 6 },
]

export const links = [
  {
    id: 1,
    title: "Next.js 공식 문서",
    url: "https://nextjs.org/docs",
    description: "Next.js의 라우팅, 렌더링, 데이터 패칭 등 공식 문서입니다.",
    folderId: 1,
    favicon: "https://nextjs.org/favicon.ico",
  },
  {
    id: 2,
    title: "Tailwind CSS",
    url: "https://tailwindcss.com",
    description: "유틸리티 클래스 기반의 CSS 프레임워크. 빠른 UI 구현에 최적화되어 있습니다.",
    folderId: 1,
    favicon: "https://tailwindcss.com/favicons/favicon.ico",
  },
  {
    id: 3,
    title: "Figma — 디자인 협업 툴",
    url: "https://figma.com",
    description: "팀과 함께 실시간으로 UI/UX 디자인을 제작하고 프로토타이핑할 수 있는 툴입니다.",
    folderId: 2,
    favicon: "https://static.figma.com/app/icon/1/favicon.ico",
  },
  {
    id: 4,
    title: "TypeScript 핸드북",
    url: "https://www.typescriptlang.org/docs/handbook/intro.html",
    description: "TypeScript의 타입 시스템과 문법을 체계적으로 배울 수 있는 공식 핸드북.",
    folderId: 1,
    favicon: "https://www.typescriptlang.org/favicon-32x32.png",
  },
  {
    id: 5,
    title: "Dribbble — 디자인 인스피레이션",
    url: "https://dribbble.com",
    description: "전 세계 디자이너들이 작업물을 공유하는 포트폴리오 & 인스피레이션 플랫폼.",
    folderId: 2,
    favicon: "https://cdn.dribbble.com/assets/favicon-b38525134603b9513174ec887944bde1a869eb6cd414f4d640ee48ab2a15a26b.ico",
  },
  {
    id: 6,
    title: "React 공식 문서",
    url: "https://react.dev",
    description: "React의 훅, 컴포넌트, 상태 관리 패턴 등을 배울 수 있는 공식 사이트.",
    folderId: 1,
    favicon: "https://react.dev/favicon.ico",
  },
  {
    id: 7,
    title: "Velog — 개발 블로그",
    url: "https://velog.io",
    description: "한국 개발자들이 기술 경험을 공유하는 마크다운 기반 블로그 플랫폼.",
    folderId: 4,
    favicon: "https://velog.io/favicon.ico",
  },
  {
    id: 8,
    title: "MDN Web Docs",
    url: "https://developer.mozilla.org",
    description: "HTML, CSS, JavaScript 등 웹 표준 기술의 레퍼런스와 가이드를 제공합니다.",
    folderId: 1,
    favicon: "https://developer.mozilla.org/favicon.ico",
  },
]
